# Generated by Django 5.1.1 on 2024-11-04 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_tagline', models.CharField(default='', max_length=200)),
                ('company_logo', models.ImageField(default='', upload_to='company_logos/')),
                ('company_location', models.CharField(max_length=200)),
                ('company_desc', models.TextField()),
                ('estblished', models.CharField(max_length=200)),
                ('company_email', models.EmailField(max_length=200, unique=True)),
                ('company_linkedin', models.URLField(max_length=500)),
                ('company_instagram', models.URLField(max_length=500)),
                ('company_facebook', models.URLField(max_length=500)),
                ('company_address', models.CharField(default='', max_length=500)),
                ('company_state', models.CharField(default='', max_length=100)),
                ('company_city', models.CharField(default='', max_length=500)),
                ('company_pincode', models.IntegerField(default=560078)),
                ('company_profile_created_at', models.DateTimeField(auto_now_add=True)),
                ('company_profile_updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Application Developer', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('job_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IN', 'Internship')], default='FT', max_length=2)),
                ('reports_to', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('summary', models.TextField()),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('preferred_qualifications', models.TextField(blank=True, null=True)),
                ('skills', models.TextField()),
                ('benefits', models.TextField(blank=True, null=True)),
                ('salary', models.CharField(default='', max_length=200)),
                ('timings', models.CharField(default='', max_length=200)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('last_date_to_apply', models.DateField(blank=True, null=True)),
                ('category', models.CharField(default='', max_length=100)),
                ('industry', models.CharField(choices=[('Tech', 'Technology'), ('Health', 'Healthcare'), ('Finance', 'Finance and Insurance'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Construction', 'Construction'), ('Education', 'Education'), ('Transport', 'Transportation and Logistics'), ('Hospitality', 'Hospitality and Tourism'), ('Govt', 'Government'), ('Telecom', 'Telecommunications'), ('Energy', 'Energy and Utilities'), ('Media', 'Media and Entertainment'), ('Pharma', 'Pharmaceuticals'), ('NonProfit', 'Non-profit Organizations'), ('Agriculture', 'Agriculture'), ('Consulting', 'Consulting'), ('Legal', 'Legal Services'), ('Fashion', 'Fashion'), ('Automotive', 'Automotive')], default='Tech', max_length=100)),
                ('company_posted_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobportal.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='applied', max_length=50)),
                ('applicant_name', models.CharField(max_length=200)),
                ('education', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('previous_companies', models.TextField(blank=True, null=True)),
                ('previous_experience', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interview_feedback', models.TextField(blank=True, null=True)),
                ('application_source', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.postjob')),
            ],
        ),
    ]
