# Generated by Django 5.1.1 on 2024-11-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuse', '0002_subscription'),
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentforCompanies',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.companyprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminuse.subscription')),
            ],
        ),
    ]
