# Generated by Django 5.1.1 on 2024-11-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('trainer', 'Trainer')], default='customer', max_length=20)),
            ],
        ),
    ]
