# Generated by Django 5.1.1 on 2024-11-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='confirm_password',
        ),
    ]
