# Generated by Django 5.1.1 on 2024-11-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agreed_to_privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
