# Generated by Django 5.1.1 on 2024-11-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuse', '0003_remove_subscription_trial_period_days'),
        ('courses', '0004_alter_course_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(blank=True, to='adminuse.addtrainers'),
        ),
    ]
