# Generated by Django 5.1.1 on 2024-11-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuse', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='trial_period_days',
        ),
    ]
